name: Release

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run tests
        run: ./kotlin test
      - name: Publish package
        run: |
          printf 'username=github-actions\npassword=%s\n' "$GITHUB_TOKEN" > creds.properties
          ./kotlin publish github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
